### ISSUE TITLE
CSS/Javascript does not appear to load from bare git pull

### ISSUE THREAD

**Issue by bubthegreat** [PureStorage-OpenConnect/FlashStache#5]
From a bare install on ubuntu xenial:

```
micheal.taylor@bubdev:~/FlashStache$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
What it looks like:
<img width="1324" alt="screen shot 2017-11-12 at 11 52 17 pm" src="https://user-images.githubusercontent.com/12198817/32713009-9230fd52-c804-11e7-846c-bc839830668d.png">

What it should look like:
<img width="715" alt="screen shot 2017-11-12 at 11 54 06 pm" src="https://user-images.githubusercontent.com/12198817/32713072-d23e959e-c804-11e7-8b42-1cb12f130e1f.png">

**Comment by richimus123** [comment]
Bub, the Nginx server (port 80) will have the static files Django will not (this is intentional design of Django with debug off).  

Due to Issue #6 which you opened the Nginx server was not forwarding properly.  I'll close this once we know that the other issue is fixed.

**Comment by richimus123** [comment]
Resolved via Nginx forwarding bug fix.
